version: "2"
linters:
  enable:
    - misspell
    - revive
    - sloglint

  settings:
    errcheck:
      exclude-functions:
        # Used in HTTP handlers, any error is handled by the server itself.
        - (net/http.ResponseWriter).Write
    revive:
      rules:
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
        - name: unused-parameter
          severity: warning
          disabled: true

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test.go

formatters:
  exclusions:
    generated: lax
